# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planet', '0007_auto_20171213_0201'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionitem',
            name='col_class',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='column class'),
        ),
    ]
